### ISSUE TITLE
Document how we should handle tailwind directives in CSS files

### ISSUE THREAD

**Issue by lgollut** [liip-lausanne/coding-standards#14]
As Tailwind grows in popularity across our projects, I think we should document how we want to handle specific features such as `@apply` or `@screen` directives in `css` files. It also involves defining when we should use utility classes instead of pure css properties in our class definitions.

**Comment by ludovicturmel** [comment]
Good idea to add some line into the doc 👍. Concerning `@apply` directive, I would say : use as much as possible, I don't see any case where you want to add your proper CSS if Tailwind classes give you what you need. Otherwise, for `@screen` directive what should we document ? breakpoint names ? Not sure IMHO can be more or less specific to the project.

**Comment by LeBenLeBen** [comment]
For me the rule should be to use regular CSS by default and only use Tailwind directives when you need values from the theme.

There’s no point in using `@apply grid` instead of `display: grid`, it doesn’t provide any added value. Even worse, it creates a new standard and lock the code base further to the framework unnecessarily.

However it makes sense to use `@apply m-2` rather than `margin: {whatever}` to match spacing used elsewhere.

**Comment by lgollut** [comment]
On our project, we defined Tailwind theme values with custom properties like so


```css
:root {
  --spacing-sm: 0.625rem;
  --spacing-base: 1.25rem;
  --spacing-md: 1.875rem;
}
```

```js
module.exports = {
  theme: {
    screens: {
      sm: 'var(--spacing-sm)',
      base: 'var(--spacing-base)',
      md: 'var(--spacing-md)',
    },
  },
};
```

It allow us to use pure `CSS` everywhere in our stylesheets and utilities in our templates when it make sense
